"use client";
import { useEffect, useRef, useState } from "react";
import cytoscape, { Core, ElementDefinition } from "cytoscape";
type Graph = { nodes: unknown[]; edges: unknown[] };
const colors: Record<string, string> = { Customer: "#4da3ff", Card: "#20d7a0", Transaction: "#ff5964", DeviceProfile: "#a879ff", EmailDomain: "#5f8cff", BillingRegion: "#ffb83d", ClosedCase: "#ef6c9e", InvestigationCase: "#d080ff" };
export function GraphEvidence({ graph }: { graph?: Graph }) {
  const ref = useRef<HTMLDivElement>(null); const cyRef = useRef<Core | null>(null); const [layout, setLayout] = useState("cose"); const [focus, setFocus] = useState("all");
  useEffect(() => { if (!ref.current || !graph) return; const elements = [...(graph.nodes as ElementDefinition[]), ...(graph.edges as ElementDefinition[])]; const cy = cytoscape({ container: ref.current, elements, wheelSensitivity: 0.2, style: [{ selector: "node", style: { "background-color": "#4da3ff", label: "data(label)", color: "#dbeafe", "font-size": "10px", "text-wrap": "wrap", "text-max-width": "100px", "border-width": "2px", "border-color": "#8fc9ff", "text-outline-color": "#07101e", "text-outline-width": "2px", "text-valign": "bottom", "text-margin-y": 7, width: 26, height: 26 } }, { selector: "edge", style: { width: 1.5, "line-color": "#54718f", "target-arrow-color": "#8fb2d4", "target-arrow-shape": "triangle", label: "data(label)", color: "#a8c2df", "font-size": "8px", "text-background-color": "#0d1b2e", "text-background-opacity": 1, "curve-style": "bezier" } }, ...Object.entries(colors).map(([type, color]) => ({ selector: `node[entity_type = "${type}"]`, style: { "background-color": color, "border-color": color, "shadow-blur": "14px", "shadow-color": color, "shadow-opacity": 0.35 } }))], layout: { name: layout } }); cyRef.current = cy; return () => { cy.destroy(); cyRef.current = null; }; }, [graph, layout]);
  useEffect(() => { const cy = cyRef.current; if (!cy) return; cy.nodes().forEach((node) => { node.style("display", focus === "all" || node.data("entity_type") === focus ? "element" : "none"); }); cy.edges().forEach((edge) => { edge.style("display", edge.source().style("display") === "none" || edge.target().style("display") === "none" ? "none" : "element"); }); }, [focus]);
  if (!graph) return <div className="graph-empty">No graph evidence returned by the investigation API.</div>;
  return <section className="graph-card"><div className="graph-toolbar"><div><h3>Investigation Graph</h3><p>Connected entities and relationships · powered by TigerGraph</p></div><div className="graph-controls"><label>Focus <select value={focus} onChange={(event) => setFocus(event.target.value)}><option value="all">All entities</option>{Object.keys(colors).map((type) => <option key={type} value={type}>{type}</option>)}</select></label><label>Layout <select value={layout} onChange={(event) => setLayout(event.target.value)}><option value="cose">Force</option><option value="breadthfirst">Hierarchy</option><option value="circle">Circle</option></select></label><button type="button" onClick={() => cyRef.current?.fit(undefined, 35)}>Fit view</button></div></div><div className="graph-legend">{Object.entries(colors).map(([type, color]) => <span key={type}><i style={{ background: color }} />{type}</span>)}</div><div className="graph-canvas" ref={ref} aria-label="Investigation subgraph" /></section>;
}
